# Generated by Django 4.0.3 on 2022-05-13 04:23

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('img_url', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('img_url', models.CharField(blank=True, max_length=400)),
                ('category', models.CharField(max_length=40)),
                ('subcategory', models.CharField(blank=True, max_length=40)),
                ('best_score', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('best_time', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('time_limit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curr_score', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('curr_time', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('tags', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(blank=True, max_length=400)),
                ('question', models.TextField()),
                ('answer', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('solution', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('best_time', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('time_limit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qe.quiz')),
            ],
        ),
    ]
