# Generated by Django 2.2.28 on 2022-07-09 02:15

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('img_url', models.CharField(blank=True, max_length=400)),
                ('category', models.CharField(max_length=40)),
                ('subcategory', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='DemoQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(blank=True, max_length=400)),
                ('question', models.TextField()),
                ('answer', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('solution', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qe.DemoQuiz')),
            ],
        ),
    ]
