# Generated by Django 4.0.3 on 2022-05-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qe', '0002_alter_quiz_best_score_alter_quiz_best_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='best_time',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
    ]
