# Generated by Django 4.0.3 on 2022-05-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qe', '0003_alter_question_best_time_alter_question_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tags',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='tags',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
