# Generated by Django 2.2.28 on 2022-07-09 16:25

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qe', '0003_auto_20220709_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(default=dict), size=None),
        ),
        migrations.AlterField(
            model_name='question',
            name='solution',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(default=dict), size=None),
        ),
    ]
