# Generated by Django 2.2.28 on 2022-08-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qe', '0004_auto_20220709_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
