# Generated by Django 2.2.28 on 2022-07-08 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
